const days = [
  { id:'03', date:'03/09', weekday:'Quinta', title:'Chegada + Bastille', mood:'Instalar, comprar o básico e caminhar sem pressa.', facts:['Sem treino','Sem estudo','Compras práticas','Jantar perto do Airbnb'], slots:[
    slot('14:15','Chegada em Paris CDG','Imigração, malas e deslocamento até a base.', [p('Chegada CDG','rotina','Terminal 2E. Com malas, táxi/app é o mais simples.','Transporte varia conforme táxi/app/trem','Nada para reservar','CDG até 1 Rue Keller: 50-75 min de táxi/app; transporte público 70-90 min.','https://www.google.com/maps/search/?api=1&query=Paris+Charles+de+Gaulle+Airport')]),
    slot('16:15','Check-in e pausa','Banho, malas e reset de voo longo.', [p('Airbnb Rue Keller','rotina','Base da viagem: 1 Rue Keller, 75011 Paris.','Já reservado','Check-in com anfitrião','Metrôs úteis: Bréguet-Sabin, Bastille, Voltaire.','https://www.google.com/maps/search/?api=1&query=1+Rue+Keller+75011+Paris')]),
    slot('17:00','Compras para o Airbnb','Água, frutas, ovos, iogurte, queijo, café, leite, vinho e snacks.', [p('Carrefour City Rue de la Roquette','compras','Mercado prático perto da base.','Compra-base €35-70','Não precisa','A pé da base: 5-8 min.','https://www.google.com/maps/search/?api=1&query=Carrefour+City+82+Rue+de+la+Roquette+Paris'), p('Pâtisserie Nanan','comida','Pão, doce ou recompensa de chegada.','Padaria/pâtisserie: econômico/médio','Não precisa','A pé da base: 2-4 min.','https://nananpatisserie.fr/','https://www.instagram.com/patisserie_nanan/')]),
    slot('18:00','Coulée Verte + Bastille','Passeio leve tipo High Line parisiense.', [p('Coulée Verte René-Dumont','visita','Jardim suspenso em antiga linha férrea.','Grátis','Não precisa','A pé até acesso Bastille: 15-20 min.','https://www.google.com/maps/search/?api=1&query=Coul%C3%A9e+Verte+Ren%C3%A9-Dumont+Paris')]),
    slot('19:30','Jantar perto do Airbnb','Escolher pelo cansaço.', [p('Jinchan Shokudo','comida','Japonês casual.','Médio: €20-30 por pessoa','Na hora ou reserva','Da base: 12-18 min.','https://jinchangroup.com/restaurant/shokudo?lang=en','https://www.instagram.com/jinchanizakaya/'), p('Buck','comida','Frango/sanduíche informal.','Econômico/médio: €15-25 por pessoa','Na hora','Da base: 8-12 min a pé.','https://www.buckandmore.com/'), p('Le Petit Keller','comida','Perto, bistrô/izakaya.','Médio: €20-35 por pessoa','Na hora','A pé da base: 1-3 min.','https://www.google.com/maps/search/?api=1&query=Le+Petit+Keller+13+Rue+Keller+Paris')])
  ]},
  { id:'04', date:'04/09', weekday:'Sexta', title:'Torre Eiffel + Rue Cler', mood:'O dia da Valentina subir a Torre.', facts:['Treino + estudo depois do café','Comprar Torre antes','Rue Cler para almoço'], slots:[
    slot('07:30','Café, treino e estudo','Café no Airbnb; depois treino 40 min + estudo 30 min.', [p('Nanan','comida','Opção prática perto da base.','Padaria/pâtisserie: econômico/médio','Não precisa','A pé: 2-4 min.','https://nananpatisserie.fr/','https://www.instagram.com/patisserie_nanan/'), p('Ten Belles Bread','comida','Pão/café mais caprichado.','Econômico/médio','Não precisa','A pé: 12-15 min.','https://www.tenbelles.com/paris-11/','https://www.instagram.com/tenbelles/')]),
    slot('10:30','Torre Eiffel','Reservar horário da manhã.', [p('Torre Eiffel - 2º andar','visita','Boa experiência sem cansar tanto.','Adulto €23,50; criança €6','Comprar antes','Da base: metrô linha 8 até École Militaire + caminhada, 35-45 min.','https://www.toureiffel.paris/en/rates-opening-times'), p('Torre Eiffel - topo','visita','Experiência completa se o clima estiver bom.','Adulto €36,70; criança €9,20','Comprar antes','Mesmo trajeto do 2º andar.','https://www.toureiffel.paris/en/rates-opening-times')]),
    slot('12:45','Rue Cler','Almoço leve ou piquenique.', [p('Piquenique Rue Cler','comida','Comprar baguete, queijo, fruta e doce.','€10-20 por pessoa','Não precisa','Da Torre: 12-18 min a pé.','https://www.google.com/maps/search/?api=1&query=Rue+Cler+Paris'), p('Le Petit Cler','comida','Bistrô clássico e familiar.','Médio: €20-35 por pessoa','Recomendável','Da Torre: 12-18 min a pé.','https://www.google.com/maps/search/?api=1&query=Le+Petit+Cler+Paris')]),
    slot('14:00','Cruzeiro pelo Sena','Passeio guiado de 1 hora com saída e retorno aos pés da Torre Eiffel.', [p('Vedettes de Paris - cruzeiro guiado','visita','Barco pelo Sena passando por Invalides, Musée d’Orsay, Louvre, Notre-Dame e outros monumentos.','Adulto €21; criança de 4 a 11 anos €10','Comprar antes recomendado','Da Rue Cler: 15-20 min a pé até o Port de Suffren. Saídas geralmente a cada 30 min.','https://www.vedettesdeparis.fr/en/vdp-cruise/guided-cruise/')]),
    slot('15:15','Jardin du Luxembourg','Descompressão pós-cruzeiro: lago dos barquinhos e carrossel.', [p('Jardin du Luxembourg','visita','Lago com barquinhos de brinquedo, carrossel antigo e playground.','Grátis; aluguel de barquinho e carrossel à parte (poucos euros)','Não precisa','Do Port de Suffren: 20-25 min a pé pelo Quai Branly e Boulevard Saint-Germain.','https://www.google.com/maps/search/?api=1&query=Jardin+du+Luxembourg+Paris')]),
    slot('18:30','Jantar - escolher uma opção','Le Relais é o retorno afetivo; as demais opções reduzem o deslocamento e oferecem estilos diferentes.', [p('Le Relais de Venise - L’Entrecôte','comida','O original da Porte Maillot: salada, contra-filé com molho secreto e pommes allumettes. Chegar antes da abertura para o primeiro serviço.','Fórmula €30 por pessoa; bebidas e sobremesas à parte','Não aceita reservas; chegar 18:20-18:30','Do Port de Suffren/Torre Eiffel: cerca de 25-35 min por metrô até 271 Boulevard Pereire. Sair por volta de 17:40; abre às 18:45.','https://relaisdevenise.com/locations/paris.php'), p('Les Cocottes','comida','Alternativa bistronômica moderna: cozinha francesa servida em cocottes de ferro, descontraída e boa com criança.','Menu de 3 etapas €45; bebidas à parte','Reservar antes','135 Rue Saint-Dominique; cerca de 15 min a pé do Port de Suffren.','https://lescocottes.paris/accueil/'), p('La Fontaine de Mars','comida','Bistrô parisiense clássico, com salão tradicional e pratos como confit de pato, blanquette, coq au vin e filé com béarnaise.','Pratos principais em geral €25-46; sobremesas €11-18','Reservar antes','129 Rue Saint-Dominique; cerca de 15 min a pé do Port de Suffren.','https://www.fontaine-de-mars.com/'), p('Les Marches','comida','Bistrô familiar e sem cerimônia, com cozinha francesa tradicional e generosa em ambiente local.','Médio: cerca de €25-40 por pessoa','Reserva recomendada','5 Rue de la Manutention, do outro lado do Sena; cerca de 15-20 min do Port de Suffren.','https://lesmarches-restaurant.com/en/')])
  ]},
  { id:'05', date:'05/09', weekday:'Sábado', title:'Mercado + Orsay + Shakespeare + Berthillon', mood:'Mercado, museu, livros, sorvete e ciência.', facts:['Marché Bastille cedo','Orsay: menor de 18 grátis','Berthillon 10h-20h','Mosquée ou Atelier como opcional'], slots:[
    slot('07:45','Marché Bastille','Comprar coisas gostosas para o café e para casa.', [p('Marché Bastille','compras','Frutas, queijo, pão, tomates, quiche e flores.','Livre','Não precisa','Da base: 10-15 min a pé.','https://www.google.com/maps/search/?api=1&query=March%C3%A9+Bastille+Paris')]),
    slot('10:00',"Musée d'Orsay",'Acervo impressionista num salão de estação de trem.', [p("Musée d'Orsay",'visita','Monet, Van Gogh, Degas; prédio já é atração à parte.','Adulto €16; menor de 18 grátis','Reservar/comprar antes recomendado','Da base: 25-35 min por metrô/ônibus.','https://www.musee-orsay.fr/en/tickets')]),
    slot('12:40','Almoço + Shakespeare and Company','Escolher almoço casual e seguir para a livraria perto de Notre-Dame.', [p('Kodawari Ramen Yokochō','comida','Alternativa de ramen imersivo na Rue Mazarine para variar da cozinha francesa.','Econômico/médio: cerca de €20-30 por pessoa','Recomendável verificar fila/reserva','Do Orsay: 15-20 min a pé ao longo do Sena; depois 10-15 min até a Shakespeare.','https://www.kodawari-ramen.com/en/'), p('Shakespeare and Company','visita','Livraria icônica em inglês.','Entrada grátis; livros à parte','Não precisa','Do Orsay: 25-30 min a pé ao longo do Sena.','https://www.shakespeareandcompany.com/','https://www.instagram.com/shakespeareandcoparis/'), p('Shakespeare and Company Café','comida','Café, bolo, quiche ou sanduíche.','€8-18 por pessoa','Não precisa','Do lado da livraria.','https://www.shakespeareandcompany.com/cafe','https://www.instagram.com/shakespeareandcocafe/')]),
    slot('13:20','Île Saint-Louis + Berthillon','Caminhada até o sorvete.', [p('Berthillon','comida','Sorvete amado do ano passado.','Sorvete pago na hora; potes a partir de €13','Não precisa','Da Shakespeare: 8-12 min a pé.','https://berthillon.fr/','https://www.instagram.com/berthillon_officiel/')]),
    slot('14:45','Jardin des Plantes','Natureza + museu.', [p('Jardin des Plantes','visita','Jardim gratuito para caminhar.','Grátis','Não precisa','Da Berthillon: 18-25 min a pé ou ônibus/táxi curto.','https://www.google.com/maps/search/?api=1&query=Jardin+des+Plantes+Paris'), p('Grande Galerie de l’Évolution','visita','Museu de animais e ciência, muito Valentina.','Adulto €13; reduzido €10','Comprar antes recomendado','Dentro do Jardin des Plantes.','https://www.jardindesplantesdeparis.fr/en/grande-galerie-de-l-evolution')]),
    slot('16:30','Escolha de fim de tarde','Escolher uma opção, não as duas.', [p('Grande Mosquée de Paris','opcional','Chá de menta, doces e mosaicos.','Visita adulto €5; reduzido €3','Não precisa','Do Jardin des Plantes: 5-8 min a pé.','https://www.grandemosqueedeparis.fr/visites','https://www.instagram.com/grandemosqueedeparis/'), p('Atelier des Lumières - O Pequeno Príncipe','opcional','Imersivo, sensorial e perto do Airbnb.','Adulto a partir de €19,50; criança a partir de €12,50','Comprar horário antes','Da base: 15-20 min a pé; do Jardin: 25-35 min.','https://www.atelier-lumieres.com/','https://www.instagram.com/atelierdeslumieres/')])
  ]},
  { id:'06', date:'06/09', weekday:'Domingo', title:'Louvre + Marais', mood:'Arte curta, mercado e Marais sem pressa.', facts:['Comprar Louvre antes','Almoço no Marché des Enfants Rouges','Jantar flexível'], slots:[
    slot('10:00','Louvre','Roteiro curto: Egito, Mona Lisa, Vênus de Milo e Vitória de Samotrácia.', [p('Louvre - roteiro curto','visita','Entrada com horário marcado; sair antes de cansar.','Adulto €32; menor de 18 grátis','Reservar/comprar antes','Da base: linha 1 Bastille > Palais Royal-Musée du Louvre, 20-30 min.','https://www.louvre.fr/en/visit/hours-admission/tickets-and-prices')]),
    slot('12:30','Palais Royal ou Tuileries','Descompressão pós-museu.', [p('Palais Royal','visita','Lindo, fotogênico e calmo.','Grátis','Não precisa','Do Louvre: 5-8 min a pé.','https://www.google.com/maps/search/?api=1&query=Palais+Royal+Paris'), p('Jardin des Tuileries','opcional','Clássico e aberto.','Grátis','Não precisa','Do Louvre: 5-10 min a pé.','https://www.google.com/maps/search/?api=1&query=Tuileries+Garden+Paris')]),
    slot('13:30','Marché des Enfants Rouges','Almoço de mercado no Marais.', [p('LULU Crêperie','comida','Galette gigante em cone.','Por volta de €13','Não precisa','Do Louvre: 20-30 min por metrô/ônibus.','https://www.instagram.com/lulu.creperie/'), p('Stand marroquino / Tom','comida','Couscous e tagine.','€10-20 por pessoa','Não precisa','Dentro do mercado.','https://www.tripadvisor.com/Search?q=March%C3%A9+des+Enfants+Rouges+Tom+Paris'), p('Corossol','comida','Comida afro-antillana.','€10-20 por pessoa','Não precisa','Dentro do mercado.','https://www.tripadvisor.com/Search?q=Corossol+March%C3%A9+des+Enfants+Rouges+Paris'), p('L’As du Fallafel','comida','Alternativa casual no Marais: falafel na Rue des Rosiers. Só vale se a fila estiver razoável.','Econômico: cerca de €10-20 por pessoa','Não precisa; pode haver fila','Do Marché des Enfants Rouges: 12-18 min a pé.','https://www.google.com/maps/search/?api=1&query=L%27As+du+Fallafel+34+Rue+des+Rosiers+Paris')]),
    slot('15:00','Marais','Passeio sem meta rígida.', [p('Place des Vosges','visita','Uma das praças mais bonitas de Paris.','Grátis','Não precisa','Do mercado: 15-20 min a pé.','https://www.google.com/maps/search/?api=1&query=Place+des+Vosges+Paris'), p('Bistrot Instinct','comida','Principal novidade gastronômica da viagem: cozinha francesa contemporânea no Haut-Marais.','Menu de verão: €51 por 2 pratos ou €63 por 3 pratos','Reservar antes','Do Marché des Enfants Rouges: 2-5 min a pé; da Place des Vosges: 15-20 min.','https://bistrotinstinctparis3.fr/fr/menu'), p('Bouillon République','comida','Jantar francês bom custo-benefício.','€15-30 por pessoa','Reserva recomendada','Da base: 18-22 min a pé.','https://linktr.ee/bouillonsrestaurants','https://www.instagram.com/bouillonsrestaurants/')])
  ]},
  { id:'07', date:'07/09', weekday:'Segunda', title:'Disneyland Paris', mood:'Favoritos sem tentar zerar dois parques.', facts:['Ingressos já comprados','Levar snacks','Treino e estudo cedo'], slots:[
    slot('06:45','Café, treino e estudo','Café no Airbnb, treino e estudo curto.', [p('Café com compras do mercado','rotina','Mais seguro para não atrasar.','Já comprado','Não precisa','Na base.','https://www.google.com/maps/search/?api=1&query=1+Rue+Keller+Paris')]),
    slot('08:15','Saída para Disney','Metrô + RER A até Marne-la-Vallée/Chessy.', [p('RER A para Disneyland Paris','rotina','Trajeto direto depois de conectar ao RER A.','Transporte à parte','Não precisa','Total 60-75 min.','https://www.google.com/maps/search/?api=1&query=Disneyland+Paris')]),
    slot('09:30','Disneyland Paris','Usar ingresso 1 dia / 2 parques.', [p('1 Dia / 2 Parques','visita','Ingressos já comprados para 07/09.','Já comprado','Já reservado','Da estação: entrada a pé.','https://www.disneylandparis.com/','https://www.instagram.com/disneylandparis/'), p('Snacks de fila','compras','Água, frutas, barrinhas/biscoitos e sanduíche simples.','Mais barato que depender só do parque','Comprar antes','Comprar no Carrefour/mercado na véspera.','https://www.google.com/maps/search/?api=1&query=Carrefour+City+82+Rue+de+la+Roquette+Paris')])
  ]},
  { id:'08', date:'08/09', weekday:'Terça', title:'Saída para Orly', mood:'Café, malas e aeroporto com folga.', facts:['Sem treino','Sem estudo','Voo 10:45'], slots:[
    slot('06:30','Café rápido no Airbnb','Usar o que sobrou das compras.', [p('Café de saída','rotina','Fruta, iogurte, pão e café.','Já comprado','Não precisa','Na base.','https://www.google.com/maps/search/?api=1&query=1+Rue+Keller+Paris')]),
    slot('07:30','Saída para Orly','Chegar por volta de 08:30.', [p('Paris Orly','rotina','Aeroporto do voo para Nápoles.','Transporte à parte','Nada a reservar agora','Táxi/app com malas: 35-60 min; transporte público possível, menos confortável.','https://www.google.com/maps/search/?api=1&query=Paris+Orly+Airport')])
  ]}
];

function slot(time,title,note,options){return{time,title,note,options};}
function p(name,category,description,cost,booking,transport,url,instagram){return{name,category,description,cost,booking,transport,url,instagram};}
const filters=['Todos','Visita','Comida','Compras','Rotina','Opcionais'];
let active=days[0].id, filter='Todos', selected=null;
const picked=new Set(JSON.parse(localStorage.getItem('paris-picked')||'[]'));
const $=s=>document.querySelector(s);
$('#printButton').onclick=()=>window.print();
function showModal(){$('#modalOverlay').classList.add('is-open');document.body.classList.add('modal-open');}
function hideModal(){$('#modalOverlay').classList.remove('is-open');document.body.classList.remove('modal-open');}
function closeModal(){hideModal();selected=null;render();}
$('#modalClose').onclick=closeModal;
$('#modalOverlay').addEventListener('click',e=>{if(e.target===$('#modalOverlay'))closeModal();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
function label(c){return{visita:'Visita',comida:'Comida',compras:'Compras',rotina:'Rotina',opcional:'Opcional'}[c]||c;}
function imgUrl(n){return `https://www.google.com/search?tbm=isch&q=${encodeURIComponent(n+' Paris photos')}`;}
function tripUrl(n){return `https://www.tripadvisor.com/Search?q=${encodeURIComponent(n+' Paris')}`;}
function mapUrl(n){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(n+' Paris')}`;}
function render(){const day=days.find(d=>d.id===active);renderDays();renderSummary(day);renderFilters();renderTimeline(day);renderDetail(selected);} 
function renderDays(){ $('#dayGrid').innerHTML=days.map(d=>`<button class="day-card ${d.id===active?'is-active':''}" data-day="${d.id}"><time>${d.weekday}<span class="day-number">${d.date}</span></time><strong>${d.title}</strong><span>${d.mood}</span></button>`).join(''); document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{active=b.dataset.day;selected=null;hideModal();render();});}
function renderSummary(d){const all=d.slots.flatMap(s=>s.options), marked=all.filter(x=>picked.has(x.name)), res=all.filter(x=>/comprar|reserv|ingresso|check-in/i.test(x.booking)&&!/não precisa|nada/i.test(x.booking)), costs=all.filter(x=>!/grátis|já comprado|já reservado|nada/i.test(x.cost)); $('#daySummary').innerHTML=`<p class="eyebrow">${d.weekday}</p><p class="summary-date">${d.date}</p><h2>${d.title}</h2><p>${d.mood}</p><ul class="summary-list">${d.facts.map(f=>`<li>${f}</li>`).join('')}<li><strong>Marcados:</strong> ${marked.length?marked.map(x=>x.name).join(', '):'nenhum ainda'}</li></ul><div class="summary-section"><h3>Reservas</h3><ul class="mini-list">${res.length?res.map(x=>`<li><strong>${x.name}:</strong> ${x.booking}</li>`).join(''):'<li>Nada obrigatório neste dia.</li>'}</ul></div><div class="summary-section"><h3>Valores</h3><ul class="mini-list">${costs.slice(0,6).map(x=>`<li><strong>${x.name}:</strong> ${x.cost}</li>`).join('')||'<li>Sem custos relevantes.</li>'}</ul></div>`;}
function renderFilters(){ $('#filterRow').innerHTML=filters.map(f=>`<button class="filter-button ${f===filter?'is-active':''}" data-filter="${f}">${f}</button>`).join(''); document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});}
function renderTimeline(d){$('#activeDateLabel').textContent=`${d.weekday}, ${d.date}`; const cat=filter.toLowerCase().replace('opcionais','opcional').replace('todos',''); $('#timeline').innerHTML=d.slots.map(s=>{const ops=s.options.filter(o=>!cat||o.category===cat); if(!ops.length)return''; return `<article class="time-block"><div class="time-label">${s.time}</div><div class="slot"><h3 class="slot-title">${s.title}</h3><p class="slot-note">${s.note}</p><div class="option-grid">${ops.map(o=>`<button class="option-card ${selected&&selected.name===o.name?'is-selected':''}" data-place="${o.name}"><h4>${o.name}</h4><div class="option-meta"><span class="tag ${o.category}">${label(o.category)}</span><span class="tag rotina">${o.booking}</span>${picked.has(o.name)?'<span class="tag visita">Marcado</span>':''}</div></button>`).join('')}</div></div></article>`;}).join('')||'<div class="empty-state">Nenhuma opção neste filtro.</div>'; document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{selected=d.slots.flatMap(s=>s.options).find(o=>o.name===b.dataset.place);render();showModal();});}
function renderDetail(o){ if(!o){$('#detailPanel').innerHTML='<p class="eyebrow">Detalhes</p><h2 class="detail-title">Selecione uma opção</h2><p class="detail-description">Custo, reserva, fotos, mapa e transporte aparecem aqui.</p>';return;} const is=picked.has(o.name); const links=[`<a class="link-button photo-link" target="_blank" href="${imgUrl(o.name)}">Ver fotos</a>`, o.url?`<a class="link-button" target="_blank" href="${o.url}">${/instagram/.test(o.url)?'Instagram':/maps|google/.test(o.url)?'Mapa':'Site'}</a>`:'', o.instagram?`<a class="link-button" target="_blank" href="${o.instagram}">Instagram</a>`:'', !o.url&&!o.instagram?`<a class="link-button" target="_blank" href="${tripUrl(o.name)}">Tripadvisor</a>`:''].join(''); $('#detailPanel').innerHTML=`<p class="eyebrow">${label(o.category)}</p><h2 class="detail-title">${o.name}</h2><p class="detail-description">${o.description}</p><ul class="detail-list"><li><strong>Quanto custa?</strong> ${o.cost}</li><li><strong>Tem que reservar?</strong> ${o.booking}</li><li><strong>Endereço/base:</strong> Airbnb em 1 Rue Keller, 75011 Paris.</li></ul><div class="logistics"><details open><summary>Transporte e deslocamento</summary><p>${o.transport}</p></details><details open><summary>Links</summary><div class="inline-links">${links}</div></details></div><div class="action-row"><button class="choice-button ${is?'is-picked':''}" id="pickButton">${is?'Remover dos escolhidos':'Marcar quero fazer'}</button><a class="link-button" target="_blank" href="${mapUrl(o.name)}">Abrir mapa</a></div>`; $('#pickButton').onclick=()=>{is?picked.delete(o.name):picked.add(o.name);localStorage.setItem('paris-picked',JSON.stringify([...picked]));render();};}
render();
