function slot(time,title,note,options){return{time,title,note,options};}
function p(name,category,description,cost,booking,transport,url,instagram){return{name,category,description,cost,booking,transport,url,instagram};}

const naplesBase = {
  title:'VAN Vieni a Napoli — Centro Storico',
  facts:['<strong>Bairro:</strong> Centro Storico / Spaccanapoli','<strong>Período:</strong> 08-13 setembro · 5 noites','<strong>Uso:</strong> deslocamentos abaixo partem desta base']
};
const monopoliBase = {
  title:'Color Dream Residence — Monopoli',
  facts:['<strong>Bairro:</strong> centro histórico de Monopoli','<strong>Período:</strong> 13-18 setembro · 5 noites','<strong>Uso:</strong> carro fica fora da ZTL; bate-voltas partem desta base']
};

const days = [
  { id:'08-it', date:'08/09', weekday:'Terça', title:'Chegada a Nápoles', mood:'Voo, check-in e primeira pizza sem superprogramar.', facts:['Voo Transavia TO3820','Somente bagagem de mão','Táxi oficial branco','Passeio leve à noite'], slots:[
    slot('10:45','Voo Paris-Orly → Nápoles','Voo direto de 2h15; chegada prevista às 13h.', [p('Transavia TO3820','rotina','Voo direto ORY–NAP para 3 passageiros.','Já comprado · R$ 2.106','Já reservado · WEZ38J','Em Paris, sair da base por volta de 07:30-08:00 para Orly.','https://www.transavia.com/')]),
    slot('13:00','Chegada e traslado','Usar apenas táxi oficial branco até o Centro Storico.', [p('Táxi oficial NAP → Centro Storico','rotina','Opção simples com bagagem de mão; não alugar carro em Nápoles.','Cerca de €25','Na hora','Aeroporto de Nápoles até o VAN Vieni a Napoli.','https://www.google.com/maps/search/?api=1&query=Naples+International+Airport')]),
    slot('16:00','Check-in e pausa','Instalar-se antes do passeio leve.', [p('VAN Vieni a Napoli','rotina','Apartamento de 2 quartos, nota 9,6, perto de Spaccanapoli.','Já pago · €610 total','Já reservado','Base no Centro Storico; atividades centrais são feitas a pé.','https://www.booking.com/hotel/it/van-vieni-a-napoli.pt-br.html')]),
    slot('18:30','Spaccanapoli + primeira pizza','Caminhada curta e jantar napolitano.', [p('Pizzeria Sorbillo','comida','Pizza napolitana DOC na Via dei Tribunali.','€ · até €15 por pessoa','Não precisa; pode haver fila','A pé a partir do Centro Storico.','https://www.google.com/maps/search/?api=1&query=Pizzeria+Sorbillo+Napoli'),p('Di Matteo','comida','Pizza napolitana e friggitoria, autêntica e econômica.','€ · até €15 por pessoa','Não precisa','A pé a partir do Centro Storico.','https://www.google.com/maps/search/?api=1&query=Di+Matteo+Napoli')])
  ]},
  { id:'09', date:'09/09', weekday:'Quarta', title:'Centro Storico + Lungomare', mood:'Nápoles a pé, com pausas e pôr do sol no mar.', facts:['Ritmo moderado','Centro a pé','Gelato no caminho','Pôr do sol no Lungomare'], slots:[
    slot('09:00','Spaccanapoli','Começar pelo eixo histórico da cidade.', [p('Spaccanapoli','visita','Ruas históricas, igrejas, lojas e vida napolitana.','Grátis','Não precisa','A pé desde a hospedagem.','https://www.google.com/maps/search/?api=1&query=Spaccanapoli+Napoli')]),
    slot('10:30','San Gregorio Armeno','Passear pela rua dos artesãos de presépios.', [p('Via San Gregorio Armeno','visita','Oficinas tradicionais e pequenas lojas no Centro Storico.','Grátis; compras à parte','Não precisa','Poucos minutos a pé de Spaccanapoli.','https://www.google.com/maps/search/?api=1&query=Via+San+Gregorio+Armeno+Napoli')]),
    slot('11:30','Duomo de Nápoles','Visita curta antes do almoço.', [p('Duomo di Napoli','visita','Catedral dedicada a San Gennaro.','Grátis','Não precisa','Cerca de 8-12 min a pé de San Gregorio Armeno.','https://www.google.com/maps/search/?api=1&query=Duomo+di+Napoli')]),
    slot('13:00','Almoço napolitano','Escolher uma opção casual.', [p('Trattoria da Nennella','comida','Cozinha tradicional, ambiente animado e familiar.','€€ · €15-35 por pessoa','Sem reserva','No Quartieri Spagnoli; usar metrô ou caminhar conforme o ritmo.','https://www.google.com/maps/search/?api=1&query=Trattoria+da+Nennella+Napoli'),p('Di Matteo','comida','Pizza e fritos para um almoço rápido no Centro Storico.','€ · até €15 por pessoa','Não precisa','Na Via dei Tribunali.','https://www.google.com/maps/search/?api=1&query=Di+Matteo+Napoli')]),
    slot('16:00','Castel dell’Ovo + Lungomare','Caminhada costeira com pôr do sol.', [p('Castel dell’Ovo','visita','Fortaleza à beira-mar e vistas do Golfo de Nápoles.','Grátis na área externa','Não precisa','Do Centro Storico: metrô/ônibus ou táxi curto; seguir a pé pelo Lungomare.','https://www.google.com/maps/search/?api=1&query=Castel+dell%27Ovo+Napoli'),p('Lungomare Caracciolo','visita','Passeio plano à beira-mar, bom para encerrar o dia.','Grátis','Não precisa','Continuação a pé desde o Castel dell’Ovo.','https://www.google.com/maps/search/?api=1&query=Lungomare+Caracciolo+Napoli')])
  ]},
  { id:'10', date:'10/09', weekday:'Quinta', title:'Vesúvio + Pompeia', mood:'Dia intenso com guia, água, tênis e protetor solar.', facts:['Tour combinado recomendado','Saída cedo','Vesúvio em espera','Pompeia: menor de 18 grátis'], slots:[
    slot('07:00','Saída com guia','Tour combinado com transporte para evitar logística fragmentada.', [p('Tour Vesúvio + Pompeia','rotina','Contratar opção com guia e transporte saindo de Nápoles.','Passeios Itália dentro do orçamento de €150-250','Reservar antes','Saída da região central de Nápoles.','https://www.google.com/search?q=tour+Vesuvio+Pompeia+saindo+de+Napoles')]),
    slot('08:30','Gran Cono do Vesúvio','Subida moderada de aproximadamente 45-60 min.', [p('Vesúvio — Gran Cono','visita','Trilha até a borda da cratera; levar água, tênis e protetor.','Cerca de €11,68 adulto; €8,55 reduzido','Comprar quando abrir, cerca de 30 dias antes','Acesso integrado ao tour; vendas oficiais pelo Vivaticket.','https://vesuviopark.vivaticket.it/en/event/gran-cono-del-vesuvio/79785')]),
    slot('12:00','Almoço leve','Lanche no caminho entre as visitas.', [p('Lanche no caminho','comida','Refeição rápida para preservar energia e tempo.','€ · até €15 por pessoa','Não precisa','Seguir a indicação logística do guia.','https://www.google.com/maps/search/?api=1&query=Pompei+restaurants')]),
    slot('13:30','Pompeia com guia','Reservar cerca de 3 horas para as ruínas.', [p('Parque Arqueológico de Pompeia','visita','Visita guiada aos principais pontos da cidade romana.','€18 adulto; menor de 18 grátis','Reservar/comprar 4-8 semanas antes','De Nápoles sem tour: Circumvesuviana, cerca de 20-40 min.','https://pompeiisites.org/en/')])
  ]},
  { id:'11', date:'11/09', weekday:'Sexta', title:'Museu + Quartieri Spagnoli', mood:'Arqueologia pela manhã e bairro espanhol à tarde.', facts:['Ritmo moderado','Maior acervo romano','Ligação com Pompeia','Jantar no próprio bairro'], slots:[
    slot('09:30','Museu Arqueológico Nacional','Rever os achados de Pompeia com contexto.', [p('MANN — Museu Arqueológico','visita','Um dos maiores acervos de arte romana, com peças de Pompeia.','Ingresso pago; consultar tarifa vigente','Comprar antes recomendado','Do Centro Storico: caminhada ou metrô curto.','https://mann-napoli.it/en/')]),
    slot('13:00','Pausa para almoço','Manter a tarde flexível.', [p('Pizzeria Sorbillo','comida','Pizza napolitana clássica no Centro Storico.','€ · até €15 por pessoa','Não precisa; pode haver fila','A pé desde a base ou do museu.','https://www.google.com/maps/search/?api=1&query=Pizzeria+Sorbillo+Napoli')]),
    slot('15:30','Quartieri Spagnoli','Explorar ruas, murais e a atmosfera do bairro.', [p('Quartieri Spagnoli','visita','Bairro vibrante para caminhar sem roteiro rígido.','Grátis','Não precisa','Metrô até Toledo ou caminhada a partir do centro.','https://www.google.com/maps/search/?api=1&query=Quartieri+Spagnoli+Napoli')]),
    slot('19:00','Jantar no bairro','Escolher entre duas trattorias tradicionais.', [p('Trattoria Quartieri Spagnoli','comida','Cozinha napolitana tradicional no bairro visitado.','€€ · €15-35 por pessoa','Reserva recomendada','Aberta sexta 12:30-16:00 e 18:30-23:30.','https://www.google.com/maps/search/?api=1&query=Trattoria+Quartieri+Spagnoli+Napoli'),p('Trattoria da Nennella','comida','Opção autêntica, animada e econômica.','€€ · €15-35 por pessoa','Sem reserva','Dentro do Quartieri Spagnoli.','https://www.google.com/maps/search/?api=1&query=Trattoria+da+Nennella+Napoli')])
  ]},
  { id:'12', date:'12/09', weekday:'Sábado', title:'Costa Amalfitana', mood:'Bate-volta de ferry para evitar trânsito e estradas cansativas.', facts:['Dia intenso','Ferry recomendado','Positano como base','Ravello opcional'], slots:[
    slot('07:45','Saída para Molo Beverello','Chegar com antecedência para o ferry.', [p('Molo Beverello','rotina','Terminal de ferries no centro de Nápoles.','Transporte local à parte','Não precisa','Táxi/metro desde o Centro Storico.','https://www.google.com/maps/search/?api=1&query=Molo+Beverello+Napoli')]),
    slot('09:00','Ferry para Positano','Travessia panorâmica, evitando a estrada costeira.', [p('Ferry Nápoles → Positano','rotina','Melhor opção indicada na planilha para o bate-volta.','Cerca de €20 por pessoa por trecho','Comprar antes','Travessia de aproximadamente 1-2 horas.','https://www.travelmar.it/en/')]),
    slot('11:00','Positano','Caminhar, apreciar as vistas e descer até a praia.', [p('Centro de Positano','visita','Ruas inclinadas, mirantes e orla da Costa Amalfitana.','Grátis; compras à parte','Não precisa','A pé a partir do porto; considerar as subidas.','https://www.google.com/maps/search/?api=1&query=Positano+Italy')]),
    slot('13:00','Almoço com vista','Restaurante confirmado aberto o dia todo.', [p('Adamo ed Eva Ristorante','comida','Cozinha mediterrânea com vista panorâmica em Positano.','€€€ · acima de €35 por pessoa','Reservar antes','Aberto diariamente, 10:00-23:00.','https://www.google.com/maps/search/?api=1&query=Adamo+ed+Eva+Ristorante+Positano')]),
    slot('15:30','Ravello ou mais tempo em Positano','Escolher conforme energia e conexões do dia.', [p('Ravello','opcional','Cidade alta com jardins e vistas; exige conexão adicional.','Transporte e entradas à parte','Verificar horários','Ônibus/ferry com conexão via Amalfi.','https://www.google.com/maps/search/?api=1&query=Ravello+Italy'),p('Praia de Positano','opcional','Alternativa simples para desacelerar antes do retorno.','Praia pública grátis; lidos pagos','Não precisa','Junto ao porto de Positano.','https://www.google.com/maps/search/?api=1&query=Spiaggia+Grande+Positano')])
  ]},
  { id:'13', date:'13/09', weekday:'Domingo', title:'Nápoles → Monopoli', mood:'Trem, retirada do carro e chegada tranquila à Puglia.', facts:['Check-out cedo','Trem direto pela manhã','Retirar carro em Bari','Atenção à ZTL'], slots:[
    slot('07:00','Check-out e Napoli Centrale','Sair cedo para o trem da manhã.', [p('Napoli Centrale','rotina','Estação de embarque para Bari.','Transporte local à parte','Não precisa','Táxi ou metrô desde o Centro Storico.','https://www.google.com/maps/search/?api=1&query=Napoli+Centrale')]),
    slot('08:00','Trem Nápoles → Bari','Priorizar trem direto entre 07:00 e 09:00.', [p('Trenitalia para Bari Centrale','rotina','Frecciarossa ou Intercity; duração aproximada de 4h.','€60-90 para 3 pessoas','Comprar 30-60 dias antes','Embarque Napoli Centrale; desembarque Bari Centrale.','https://www.trenitalia.com/')]),
    slot('12:30','Retirada do carro','Compacto automático é suficiente com malas de mão.', [p('Toyota Yaris — Centauro','rotina','Categoria recomendada, fornecedor nota 8,1.','€242 por 5 dias; Kasko e combustível à parte','Reservar antes','Retirada Bari Centrale; devolução Bari Aeroporto.','https://www.rentalcars.com/en/city/it/bari/?puDay=13&puMonth=9&puYear=2026&doDay=18&doMonth=9&doYear=2026&ftsType=t&ftsAutocomplete=Bari+Train+Station&dropLocationName=Bari+Airport')]),
    slot('14:00','Chegada e check-in em Monopoli','Estacionar fora do centro histórico e entrar a pé.', [p('Color Dream Residence','rotina','Hospedagem no centro histórico de Monopoli, nota 9,6.','Já pago · €819 total','Já reservado','Carro fica fora da ZTL; centro é percorrido a pé.','https://www.booking.com/hotel/it/color-dream-residence.pt-br.html')]),
    slot('19:30','Jantar em Monopoli','Restaurante confirmado aberto no domingo.', [p('My Wine — Il Piacere del Palato','comida','Wine bar e cozinha contemporânea no centro.','€€ · €15-35 por pessoa','Reserva recomendada','Aberto domingo 13:00-15:00 e 19:30-23:00.','https://www.google.com/maps/search/?api=1&query=My+Wine+Il+Piacere+del+Palato+Monopoli')])
  ]},
  { id:'14', date:'14/09', weekday:'Segunda', title:'Alberobello', mood:'Chegar antes das multidões e explorar os trulli com calma.', facts:['Saída antes das 09:00','18 km de Monopoli','Centro a pé','Orecchiette no almoço'], slots:[
    slot('08:30','Saída de Monopoli','Chegar antes das 10h.', [p('Carro até Alberobello','rotina','Bate-volta curto pela Puglia.','Combustível incluso na estimativa geral','Não precisa','Cerca de 18 km; estacionar fora do centro turístico.','https://www.google.com/maps/dir/Monopoli/Alberobello')]),
    slot('09:15','Rione Monti e trulli','Explorar as casas cônicas do sítio UNESCO.', [p('Trulli de Alberobello','visita','Arquitetura única da Puglia e ruas fotogênicas.','Grátis; museus e compras à parte','Não precisa','Percurso principal feito a pé.','https://www.google.com/maps/search/?api=1&query=Trulli+di+Alberobello')]),
    slot('12:30','Almoço pugliano','Orecchiette, burrata e pratos típicos.', [p('La Cantina di Dio Vincenzo','comida','Cozinha pugliana típica com massas frescas.','€€ · €15-35 por pessoa','Reserva recomendada','No centro de Alberobello.','https://www.google.com/maps/search/?api=1&query=La+Cantina+di+Dio+Vincenzo+Alberobello')]),
    slot('15:00','Retorno com tarde livre','Descansar ou caminhar por Monopoli.', [p('Centro histórico de Monopoli','opcional','Ruas, porto antigo e praia urbana perto da hospedagem.','Grátis','Não precisa','A pé desde o Color Dream.','https://www.google.com/maps/search/?api=1&query=Centro+Storico+Monopoli')])
  ]},
  { id:'15', date:'15/09', weekday:'Terça', title:'Polignano a Mare + lido', mood:'Falésias, mar e estrutura de praia para a família.', facts:['9 km de Monopoli','Praia paga recomendada','Gelato no caminho','Jantar de frutos do mar'], slots:[
    slot('09:00','Saída para Polignano','Bate-volta curto de carro.', [p('Carro até Polignano a Mare','rotina','Trajeto rápido pela costa.','Combustível incluso na estimativa','Não precisa','Cerca de 9 km; procurar estacionamento fora do centro.','https://www.google.com/maps/dir/Monopoli/Polignano+a+Mare')]),
    slot('09:30','Centro e mirantes','Caminhar pela aldeia branca sobre as falésias.', [p('Polignano a Mare','visita','Centro histórico, mirantes e vistas do Adriático.','Grátis','Não precisa','Percurso a pé a partir do estacionamento.','https://www.google.com/maps/search/?api=1&query=Polignano+a+Mare')]),
    slot('11:30','Praia com estrutura','Em setembro, preferir um lido pago.', [p('Lido em Polignano','visita','Espreguiçadeiras, banheiro e apoio para um dia de praia confortável.','Pago; consultar diária do lido','Reservar recomendado','Escolher opção com estacionamento ou acesso simples.','https://www.google.com/maps/search/?api=1&query=lido+Polignano+a+Mare')]),
    slot('16:00','Gelato e passeio final','Parada doce antes de voltar.', [p('Gelato em Polignano','comida','Pausa inspirada na terra de Domenico Modugno.','€ · até €15 por pessoa','Não precisa','No centro histórico.','https://www.google.com/maps/search/?api=1&query=gelato+Polignano+a+Mare')]),
    slot('19:30','Jantar de frutos do mar','Opção clássica indicada na planilha.', [p('Ristorante Da Tuccino','comida','Peixe fresco e frutos do mar com vista.','€€€ · acima de €35 por pessoa','Reservar antes','Em Polignano a Mare; confirmar horário antes do retorno.','https://www.google.com/maps/search/?api=1&query=Ristorante+Da+Tuccino+Polignano+a+Mare')])
  ]},
  { id:'16', date:'16/09', weekday:'Quarta', title:'Ostuni + Castellana', mood:'Cidade branca e cavernas num dia moderado.', facts:['34 km até Ostuni','Cavernas agradam crianças','Reservar visita','Tênis confortável'], slots:[
    slot('08:30','Saída para Ostuni','Ir cedo para caminhar com temperatura agradável.', [p('Carro até Ostuni','rotina','Bate-volta desde Monopoli.','Combustível incluso na estimativa','Não precisa','Cerca de 34 km; estacionar fora do centro histórico.','https://www.google.com/maps/dir/Monopoli/Ostuni')]),
    slot('09:30','Centro histórico de Ostuni','Explorar a Cidade Branca medieval.', [p('Ostuni — Cidade Branca','visita','Ruas caiadas, escadarias e vistas do vale.','Grátis','Não precisa','Centro histórico a pé; atenção às ladeiras.','https://www.google.com/maps/search/?api=1&query=Centro+Storico+Ostuni')]),
    slot('12:30','Almoço ou lanche','Pausa antes das cavernas.', [p('Almoço em Ostuni','comida','Escolher refeição leve para seguir viagem.','€€ · €15-35 por pessoa','Não precisa','No centro ou próximo ao estacionamento.','https://www.google.com/maps/search/?api=1&query=restaurants+Ostuni')]),
    slot('15:00','Grotte di Castellana','Visita guiada às cavernas subterrâneas.', [p('Grotte di Castellana','visita','Formações subterrâneas e passeio marcante para crianças.','Family cerca de €58-61 online','Reservar 2-4 semanas antes','De Ostuni, seguir de carro; levar calçado firme.','https://www.grottedicastellana.it/en/')]),
    slot('19:30','Jantar em Ostuni ou Monopoli','Escolher conforme o cansaço.', [p('Ostuni Palace Bistrot','comida','Cozinha pugliana contemporânea, nota 4,8.','€€ · €15-35 por pessoa','Reservar recomendado','Aberto diariamente 19:30-22:30.','https://www.google.com/maps/search/?api=1&query=Ostuni+Palace+Bistrot'),p('Al Mare','comida','Pizzaria-bistrô e frutos do mar perto do mar em Monopoli.','€€ · €15-35 por pessoa','Reserva recomendada','Boa alternativa ao retornar para a base.','https://www.google.com/maps/search/?api=1&query=Al+Mare+Monopoli')])
  ]},
  { id:'17', date:'17/09', weekday:'Quinta', title:'Matera — Sassi', mood:'Bairros-caverna, vistas e pedras: caminhar sem pressa.', facts:['Saída por volta das 08:00','1h15 de carro','Sassi só a pé','Casa Grotta opcional'], slots:[
    slot('08:00','Saída para Matera','Estacionar fora do centro e entrar a pé.', [p('Carro Monopoli → Matera','rotina','Bate-volta até a Basilicata.','Combustível e estacionamento à parte','Não precisa','Cerca de 1h15; respeitar ZTL e estacionar fora dos Sassi.','https://www.google.com/maps/dir/Monopoli/Matera')]),
    slot('09:30','Sassi di Matera','Caminhar pelos bairros-caverna Patrimônio UNESCO.', [p('Sassi di Matera','visita','Paisagem histórica única, ótima para fotos em família.','Grátis nas áreas públicas','Não precisa','Percurso de pedra, com escadas e trechos escorregadios.','https://www.google.com/maps/search/?api=1&query=Sassi+di+Matera')]),
    slot('12:30','Almoço com vista','Osteria indicada na planilha.', [p('La Nicchia Nel Sasso','comida','Cozinha contemporânea com vista para os Sassi.','€€ · €15-35 por pessoa','Reservar antes','Aberta quinta 12:00-15:00 e 19:00-23:00.','https://www.google.com/maps/search/?api=1&query=La+Nicchia+Nel+Sasso+Matera')]),
    slot('14:30','Casa-caverna','Mostrar como se vivia nos Sassi.', [p('Casa Grotta','opcional','Museu pequeno dentro de uma antiga casa-caverna.','Ingresso pago','Não precisa','Escolher uma Casa Grotta próxima ao percurso.','https://www.google.com/maps/search/?api=1&query=Casa+Grotta+Matera')]),
    slot('16:30','Retorno a Monopoli','Voltar antes do anoitecer e descansar.', [p('Retorno pela estrada','rotina','Fim do último bate-volta da viagem.','Combustível incluso na estimativa geral','Não precisa','Cerca de 1h15 até Monopoli.','https://www.google.com/maps/dir/Matera/Monopoli')])
  ]},
  { id:'18', date:'18/09', weekday:'Sexta', title:'Bari + voo para Paris', mood:'Manhã em Bari, devolução do carro e aeroporto com folga.', facts:['Voo AF1289 às 17:30','Check-in limite 16:50','Devolver carro no BRI','Noite na Casa da Camila'], slots:[
    slot('08:00','Check-out em Monopoli','Arrumar malas e seguir para Bari.', [p('Color Dream — check-out','rotina','Encerrar a estadia de cinco noites em Monopoli.','Já pago','Já reservado','Retirar o carro do estacionamento fora da ZTL.','https://www.booking.com/hotel/it/color-dream-residence.pt-br.html')]),
    slot('09:30','Bari Vecchia','Manhã livre no centro histórico.', [p('Bari Vecchia','visita','Ruas antigas, igrejas e atmosfera local antes do voo.','Grátis','Não precisa','Estacionar fora do centro histórico e seguir a pé.','https://www.google.com/maps/search/?api=1&query=Bari+Vecchia')]),
    slot('11:00','Focaccia em Bari','Parada recomendada antes de seguir ao aeroporto.', [p('Panificio Santa Rita','comida','Padaria e pasticceria clássica, nota 4,8.','€ · até €15 por pessoa','Não precisa','Aberta sexta 08:50-14:00 em Bari Vecchia.','https://www.google.com/maps/search/?api=1&query=Panificio+Santa+Rita+Bari')]),
    slot('14:30','Devolução do carro no BRI','Chegar com margem para vistoria e check-in.', [p('Devolução Centauro — Bari Aeroporto','rotina','Fim do aluguel iniciado em Bari Centrale.','Incluído no aluguel','Já reservado após contratação','Do centro de Bari ao aeroporto; prever trânsito e abastecimento.','https://www.google.com/maps/search/?api=1&query=Bari+Airport+car+rental+return')]),
    slot('17:30','Voo Bari → Paris-CDG','Voo direto Air France, chegada no Terminal 2F.', [p('Air France AF1289','rotina','Voo direto para 3 passageiros, assentos 8A/8B/8C.','Já comprado · R$ 1.665,98','Já reservado · ZK9ABQ','Check-in limite 16:50; chegada prevista em CDG às 20:05.','https://www.airfrance.com.br')])
  ]}
];

const filters=['Todos','Visita','Comida','Compras','Rotina','Opcionais'];
let active=days[0].id, filter='Todos', selected=null;
const picked=new Set(JSON.parse(localStorage.getItem('italia-picked')||'[]'));
const $=s=>document.querySelector(s);
$('#printButton').onclick=()=>window.print();
function label(c){return{visita:'Visita',comida:'Comida',compras:'Compras',rotina:'Rotina',opcional:'Opcional'}[c]||c;}
function imgUrl(n){return `https://www.google.com/search?tbm=isch&q=${encodeURIComponent(n+' Itália fotos')}`;}
function tripUrl(n){return `https://www.tripadvisor.com/Search?q=${encodeURIComponent(n+' Italy')}`;}
function mapUrl(n){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(n+' Italy')}`;}
function currentBase(){return Number(active.slice(0,2))<=12?naplesBase:monopoliBase;}
function render(){const day=days.find(d=>d.id===active);renderBase();renderDays();renderSummary(day);renderFilters();renderTimeline(day);renderDetail(selected);}
function renderBase(){const base=currentBase();$('#baseTitle').textContent=base.title;$('#baseGrid').innerHTML=base.facts.map(f=>`<span>${f}</span>`).join('');}
function renderDays(){ $('#dayGrid').innerHTML=days.map(d=>`<button class="day-card ${d.id===active?'is-active':''}" data-day="${d.id}"><time>${d.weekday}<span class="day-number">${d.date}</span></time><strong>${d.title}</strong><span>${d.mood}</span></button>`).join(''); document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{active=b.dataset.day;selected=null;render();});}
function renderSummary(d){const all=d.slots.flatMap(s=>s.options), marked=all.filter(x=>picked.has(x.name)), res=all.filter(x=>/comprar|reserv|ingresso|check-in/i.test(x.booking)&&!/não precisa|nada/i.test(x.booking)), costs=all.filter(x=>!/grátis|já comprado|já reservado|nada/i.test(x.cost)); $('#daySummary').innerHTML=`<p class="eyebrow">${d.weekday}</p><p class="summary-date">${d.date}</p><h2>${d.title}</h2><p>${d.mood}</p><ul class="summary-list">${d.facts.map(f=>`<li>${f}</li>`).join('')}<li><strong>Marcados:</strong> ${marked.length?marked.map(x=>x.name).join(', '):'nenhum ainda'}</li></ul><div class="summary-section"><h3>Reservas</h3><ul class="mini-list">${res.length?res.map(x=>`<li><strong>${x.name}:</strong> ${x.booking}</li>`).join(''):'<li>Nada obrigatório neste dia.</li>'}</ul></div><div class="summary-section"><h3>Valores</h3><ul class="mini-list">${costs.slice(0,6).map(x=>`<li><strong>${x.name}:</strong> ${x.cost}</li>`).join('')||'<li>Sem custos relevantes.</li>'}</ul></div>`;}
function renderFilters(){ $('#filterRow').innerHTML=filters.map(f=>`<button class="filter-button ${f===filter?'is-active':''}" data-filter="${f}">${f}</button>`).join(''); document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});}
function renderTimeline(d){$('#activeDateLabel').textContent=`${d.weekday}, ${d.date}`; const cat=filter.toLowerCase().replace('opcionais','opcional').replace('todos',''); $('#timeline').innerHTML=d.slots.map(s=>{const ops=s.options.filter(o=>!cat||o.category===cat); if(!ops.length)return''; return `<article class="time-block"><div class="time-label">${s.time}</div><div class="slot"><h3 class="slot-title">${s.title}</h3><p class="slot-note">${s.note}</p><div class="option-grid">${ops.map(o=>`<button class="option-card ${selected&&selected.name===o.name?'is-selected':''}" data-place="${o.name}"><h4>${o.name}</h4><div class="option-meta"><span class="tag ${o.category}">${label(o.category)}</span><span class="tag rotina">${o.booking}</span>${picked.has(o.name)?'<span class="tag visita">Marcado</span>':''}</div></button>`).join('')}</div></div></article>`;}).join('')||'<div class="empty-state">Nenhuma opção neste filtro.</div>'; document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{selected=d.slots.flatMap(s=>s.options).find(o=>o.name===b.dataset.place);render();});}
function renderDetail(o){ if(!o){$('#detailPanel').innerHTML='<p class="eyebrow">Detalhes</p><h2 class="detail-title">Selecione uma opção</h2><p class="detail-description">Custo, reserva, fotos, mapa e transporte aparecem aqui.</p>';return;} const is=picked.has(o.name); const base=currentBase(); const links=[`<a class="link-button photo-link" target="_blank" rel="noopener" href="${imgUrl(o.name)}">Ver fotos</a>`, o.url?`<a class="link-button" target="_blank" rel="noopener" href="${o.url}">${/instagram/.test(o.url)?'Instagram':/maps|google/.test(o.url)?'Mapa':'Site'}</a>`:'', o.instagram?`<a class="link-button" target="_blank" rel="noopener" href="${o.instagram}">Instagram</a>`:'', !o.url&&!o.instagram?`<a class="link-button" target="_blank" rel="noopener" href="${tripUrl(o.name)}">Tripadvisor</a>`:''].join(''); $('#detailPanel').innerHTML=`<p class="eyebrow">${label(o.category)}</p><h2 class="detail-title">${o.name}</h2><p class="detail-description">${o.description}</p><ul class="detail-list"><li><strong>Quanto custa?</strong> ${o.cost}</li><li><strong>Tem que reservar?</strong> ${o.booking}</li><li><strong>Endereço/base:</strong> ${base.title}.</li></ul><div class="logistics"><details open><summary>Transporte e deslocamento</summary><p>${o.transport}</p></details><details open><summary>Links</summary><div class="inline-links">${links}</div></details></div><div class="action-row"><button class="choice-button ${is?'is-picked':''}" id="pickButton">${is?'Remover dos escolhidos':'Marcar quero fazer'}</button><a class="link-button" target="_blank" rel="noopener" href="${mapUrl(o.name)}">Abrir mapa</a></div>`; $('#pickButton').onclick=()=>{is?picked.delete(o.name):picked.add(o.name);localStorage.setItem('italia-picked',JSON.stringify([...picked]));render();};}
render();
